name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  create-assets:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Build the binary for each OS
      - name: Build Binary
        run: |
          # Sample build commands; modify based on your project
          cargo build --release
          mkdir -p dist
          cp target/release/my_binary dist/my_binary-${{ matrix.os }}

      # Upload the built binaries as release assets
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/my_binary-${{ matrix.os }}
          asset_name: my_binary-${{ matrix.os }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
