name: Build Binaries

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  create-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Get Architecture
        id: arch
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
        shell: bash

      - name: Build Binary
        run: |
          cargo build --release
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/release/${{ github.event.repository.name }}.exe dist/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}.exe
          else
            cp target/release/${{ github.event.repository.name }} dist/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}
          fi
        shell: bash

      - name: Archive Binary
        run: |
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            zip ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}.zip *.exe
          else
            tar -czf ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}.tar.gz ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}
          fi
        shell: bash

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            dist/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}.*
          asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}-${{ env.ARCH }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
